version: 2
jobs:
  build:
    docker:
      - image: circleci/python:3.7.0
    working_directory: ~/papyrus
    steps:
      - checkout

      - restore_cache:
          keys:
          - v1-dependencies-{{ checksum "Pipfile.lock" }}
          # fallback to using ddthe latest cache if no exact match is found
          - v1-dependencies-

      - run:
          name: install system dependencies
          command: pip install pipenv --upgrade

      - run:
          name: install dependencies
          command: pipenv install --dev --deploy

      - save_cache:
          paths:
            - ./venv
          key: v1-dependencies-{{ checksum "Pipfile.lock" }}

      - run:
          name: run tests
          command: pipenv run pytest

      - run:
          name: run flake8
          command: pipenv run flake8 . --output-file test-reports
